services:
    mosparo.client:
        class: Mosparo\MosparoBundle\Services\MosparoClient
        lazy: true
        arguments:
            - '%mosparo.instance_url%'
            - '%mosparo.public_key%'
            - '%mosparo.private_key%'
            - '%mosparo.guzzle_options%'

    Mosparo\MosparoBundle\Form\Type\MosparoType:
        arguments:
            - '%mosparo.default_project%'
            - '@parameter_bag'
            - '%mosparo.enabled%'
        tags:
            - { name: form.type }

    Mosparo\MosparoBundle\Validator\IsValidMosparoValidator:
        arguments:
            - '@request_stack'
            - '@parameter_bag'
            - '%mosparo.enabled%'
        tags:
            - { name: validator.constraint_validator, alias: is_valid_mosparo_validator }
